/* AUTOGENERATED BY timepack.c, DO NOT MODIFY */
#define TIMELINE_COLS (7)
#define TIMELINE_ROWS (6)
static const unsigned char timeline_ranges[7] = {
	40, 2, 12, 0, 10, 20, 1};
static const unsigned char timeline_times[6] = {
	0, 128, 128, 64, 64, 64
};
static const unsigned char timeline_values[42] = {
	255, 159, 159, 127, 127, 127,
	223, 223, 223, 223, 223, 223,
	138, 116, 116, 233, 244, 255,
	0, 0, 0, 0, 0, 0,
	127, 127, 255, 127, 127, 127,
	127, 127, 255, 127, 127, 127,
	127, 127, 127, 127, 127, 255
};
