/* AUTOGENERATED BY timepack.c, DO NOT MODIFY */
#define TIMELINE_COLS (7)
#define TIMELINE_ROWS (6)
static const float timeline_ranges[7] = {
	40.000000, 1.500000, 12.000000, 0.000000, 10.000000, 20.000000, 1.000000};
static const unsigned char timeline_times[6] = {
	0, 210, 20, 30, 140, 10
};
static const unsigned char timeline_values[42] = {
	255, 159, 159, 127, 127, 127,
	255, 255, 255, 255, 255, 255,
	138, 116, 116, 233, 244, 255,
	0, 0, 0, 0, 0, 0,
	127, 127, 255, 127, 127, 127,
	127, 127, 255, 127, 127, 127,
	127, 127, 127, 127, 127, 255
};
