; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

	TITLE	C:\4k_intro\pbr-whitespace-master\src\ext.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?myglfunc@@3PAPAXA				; myglfunc
_BSS	SEGMENT
?myglfunc@@3PAPAXA DD 09H DUP (?)			; myglfunc
_BSS	ENDS
CONST	SEGMENT
$SG44091 DB	'glCreateProgram', 00H
$SG44092 DB	'glCreateShader', 00H
	ORG $+1
$SG44093 DB	'glShaderSource', 00H
	ORG $+1
$SG44094 DB	'glCompileShader', 00H
$SG44095 DB	'glAttachShader', 00H
	ORG $+1
$SG44096 DB	'glLinkProgram', 00H
	ORG $+2
$SG44097 DB	'glUseProgram', 00H
	ORG $+3
$SG44098 DB	'glUniform1i', 00H
$SG44099 DB	'glGetUniformLocation', 00H
CONST	ENDS
PUBLIC	?EXT_Init@@YGXXZ				; EXT_Init
EXTRN	__imp__wglGetProcAddress@4:PROC
; Function compile flags: /Ogspy
; File c:\4k_intro\pbr-whitespace-master\src\ext.cpp
;	COMDAT ?EXT_Init@@YGXXZ
_TEXT	SEGMENT
?EXT_Init@@YGXXZ PROC					; EXT_Init, COMDAT

; 21   : {

	push	esi

; 22   : 	myglfunc[0] = wglGetProcAddress("glCreateProgram");

	mov	esi, DWORD PTR __imp__wglGetProcAddress@4
	push	OFFSET $SG44091
	call	esi

; 23   : 	myglfunc[1] = wglGetProcAddress("glCreateShader");

	push	OFFSET $SG44092
	mov	DWORD PTR ?myglfunc@@3PAPAXA, eax
	call	esi

; 24   : 	myglfunc[2] = wglGetProcAddress("glShaderSource");

	push	OFFSET $SG44093
	mov	DWORD PTR ?myglfunc@@3PAPAXA+4, eax
	call	esi

; 25   : 	myglfunc[3] = wglGetProcAddress("glCompileShader");

	push	OFFSET $SG44094
	mov	DWORD PTR ?myglfunc@@3PAPAXA+8, eax
	call	esi

; 26   : 	myglfunc[4] = wglGetProcAddress("glAttachShader");

	push	OFFSET $SG44095
	mov	DWORD PTR ?myglfunc@@3PAPAXA+12, eax
	call	esi

; 27   : 	myglfunc[5] = wglGetProcAddress("glLinkProgram");

	push	OFFSET $SG44096
	mov	DWORD PTR ?myglfunc@@3PAPAXA+16, eax
	call	esi

; 28   : 	myglfunc[6] = wglGetProcAddress("glUseProgram");

	push	OFFSET $SG44097
	mov	DWORD PTR ?myglfunc@@3PAPAXA+20, eax
	call	esi

; 29   : 	myglfunc[7] = wglGetProcAddress("glUniform1i");

	push	OFFSET $SG44098
	mov	DWORD PTR ?myglfunc@@3PAPAXA+24, eax
	call	esi

; 30   : 	myglfunc[8] = wglGetProcAddress("glGetUniformLocation");

	push	OFFSET $SG44099
	mov	DWORD PTR ?myglfunc@@3PAPAXA+28, eax
	call	esi
	mov	DWORD PTR ?myglfunc@@3PAPAXA+32, eax
	pop	esi

; 31   : }

	ret	0
?EXT_Init@@YGXXZ ENDP					; EXT_Init
_TEXT	ENDS
END
