; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	C:\Users\w23\Revision2017_4k\pbr-whitespace-master\src\ext.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?oglCreateShader@@3P6GII@ZA			; oglCreateShader
PUBLIC	?oglShaderSource@@3P6GXIHPAPBDPBH@ZA		; oglShaderSource
PUBLIC	?oglCompileShader@@3P6GXI@ZA			; oglCompileShader
PUBLIC	?oglCreateProgram@@3P6GIXZA			; oglCreateProgram
PUBLIC	?oglAttachShader@@3P6GXII@ZA			; oglAttachShader
PUBLIC	?oglLinkProgram@@3P6GXI@ZA			; oglLinkProgram
PUBLIC	?oglUseProgram@@3P6GXI@ZA			; oglUseProgram
PUBLIC	?oglGetUniformLocation@@3P6GHIPBD@ZA		; oglGetUniformLocation
PUBLIC	?oglUniform1i@@3P6GXHH@ZA			; oglUniform1i
PUBLIC	?oglUniform1f@@3P6GXHM@ZA			; oglUniform1f
PUBLIC	?oglUniform2f@@3P6GXHMM@ZA			; oglUniform2f
PUBLIC	?oglUniform3f@@3P6GXHMMM@ZA			; oglUniform3f
PUBLIC	?oglGenFramebuffers@@3P6GXHPAI@ZA		; oglGenFramebuffers
PUBLIC	?oglBindFramebuffer@@3P6GXII@ZA			; oglBindFramebuffer
PUBLIC	?oglFramebufferTexture2D@@3P6GXIIIIH@ZA		; oglFramebufferTexture2D
_BSS	SEGMENT
?oglCreateShader@@3P6GII@ZA DD 01H DUP (?)		; oglCreateShader
?oglShaderSource@@3P6GXIHPAPBDPBH@ZA DD 01H DUP (?)	; oglShaderSource
?oglCompileShader@@3P6GXI@ZA DD 01H DUP (?)		; oglCompileShader
?oglCreateProgram@@3P6GIXZA DD 01H DUP (?)		; oglCreateProgram
?oglAttachShader@@3P6GXII@ZA DD 01H DUP (?)		; oglAttachShader
?oglLinkProgram@@3P6GXI@ZA DD 01H DUP (?)		; oglLinkProgram
?oglUseProgram@@3P6GXI@ZA DD 01H DUP (?)		; oglUseProgram
?oglGetUniformLocation@@3P6GHIPBD@ZA DD 01H DUP (?)	; oglGetUniformLocation
?oglUniform1i@@3P6GXHH@ZA DD 01H DUP (?)		; oglUniform1i
?oglUniform1f@@3P6GXHM@ZA DD 01H DUP (?)		; oglUniform1f
?oglUniform2f@@3P6GXHMM@ZA DD 01H DUP (?)		; oglUniform2f
?oglUniform3f@@3P6GXHMMM@ZA DD 01H DUP (?)		; oglUniform3f
?oglGenFramebuffers@@3P6GXHPAI@ZA DD 01H DUP (?)	; oglGenFramebuffers
?oglBindFramebuffer@@3P6GXII@ZA DD 01H DUP (?)		; oglBindFramebuffer
?oglFramebufferTexture2D@@3P6GXIIIIH@ZA DD 01H DUP (?)	; oglFramebufferTexture2D
_BSS	ENDS
CONST	SEGMENT
$SG44127 DB	'glCreateShader', 00H
	ORG $+1
$SG44128 DB	'glShaderSource', 00H
	ORG $+1
$SG44129 DB	'glCompileShader', 00H
$SG44130 DB	'glCreateProgram', 00H
$SG44131 DB	'glAttachShader', 00H
	ORG $+1
$SG44132 DB	'glLinkProgram', 00H
	ORG $+2
$SG44133 DB	'glUseProgram', 00H
	ORG $+3
$SG44134 DB	'glGetUniformLocation', 00H
	ORG $+3
$SG44135 DB	'glUniform1i', 00H
$SG44136 DB	'glUniform1f', 00H
$SG44137 DB	'glUniform2f', 00H
$SG44138 DB	'glUniform3f', 00H
$SG44139 DB	'glGenFramebuffers', 00H
	ORG $+2
$SG44140 DB	'glBindFramebuffer', 00H
	ORG $+2
$SG44141 DB	'glFramebufferTexture2D', 00H
CONST	ENDS
PUBLIC	?EXT_Init@@YGXXZ				; EXT_Init
EXTRN	__imp__wglGetProcAddress@4:PROC
; Function compile flags: /Ogspy
; File c:\users\w23\revision2017_4k\pbr-whitespace-master\src\ext.cpp
;	COMDAT ?EXT_Init@@YGXXZ
_TEXT	SEGMENT
?EXT_Init@@YGXXZ PROC					; EXT_Init, COMDAT

; 23   : {

	push	esi

; 24   : #define FUNCLIST_DO(T, N) ogl##N = (T)wglGetProcAddress("gl" # N);
; 25   : 	FUNCLIST FUNCLIST_DBG

	mov	esi, DWORD PTR __imp__wglGetProcAddress@4
	push	OFFSET $SG44127
	call	esi
	push	OFFSET $SG44128
	mov	DWORD PTR ?oglCreateShader@@3P6GII@ZA, eax ; oglCreateShader
	call	esi
	push	OFFSET $SG44129
	mov	DWORD PTR ?oglShaderSource@@3P6GXIHPAPBDPBH@ZA, eax ; oglShaderSource
	call	esi
	push	OFFSET $SG44130
	mov	DWORD PTR ?oglCompileShader@@3P6GXI@ZA, eax ; oglCompileShader
	call	esi
	push	OFFSET $SG44131
	mov	DWORD PTR ?oglCreateProgram@@3P6GIXZA, eax ; oglCreateProgram
	call	esi
	push	OFFSET $SG44132
	mov	DWORD PTR ?oglAttachShader@@3P6GXII@ZA, eax ; oglAttachShader
	call	esi
	push	OFFSET $SG44133
	mov	DWORD PTR ?oglLinkProgram@@3P6GXI@ZA, eax ; oglLinkProgram
	call	esi
	push	OFFSET $SG44134
	mov	DWORD PTR ?oglUseProgram@@3P6GXI@ZA, eax ; oglUseProgram
	call	esi
	push	OFFSET $SG44135
	mov	DWORD PTR ?oglGetUniformLocation@@3P6GHIPBD@ZA, eax ; oglGetUniformLocation
	call	esi
	push	OFFSET $SG44136
	mov	DWORD PTR ?oglUniform1i@@3P6GXHH@ZA, eax ; oglUniform1i
	call	esi
	push	OFFSET $SG44137
	mov	DWORD PTR ?oglUniform1f@@3P6GXHM@ZA, eax ; oglUniform1f
	call	esi
	push	OFFSET $SG44138
	mov	DWORD PTR ?oglUniform2f@@3P6GXHMM@ZA, eax ; oglUniform2f
	call	esi
	push	OFFSET $SG44139
	mov	DWORD PTR ?oglUniform3f@@3P6GXHMMM@ZA, eax ; oglUniform3f
	call	esi
	push	OFFSET $SG44140
	mov	DWORD PTR ?oglGenFramebuffers@@3P6GXHPAI@ZA, eax ; oglGenFramebuffers
	call	esi
	push	OFFSET $SG44141
	mov	DWORD PTR ?oglBindFramebuffer@@3P6GXII@ZA, eax ; oglBindFramebuffer
	call	esi
	mov	DWORD PTR ?oglFramebufferTexture2D@@3P6GXIIIIH@ZA, eax ; oglFramebufferTexture2D
	pop	esi

; 26   : #undef FUNCLIST_DO
; 27   : }

	ret	0
?EXT_Init@@YGXXZ ENDP					; EXT_Init
_TEXT	ENDS
END
